---

title: "PawVision Documentation"
description: "A Raspberry Pi-based Pet TV system with web interface"
url: "https://mkroemer.github.io/PawVision"
author: "mkroemer"
remote_theme: daattali/beautiful-jekyll@master

# Navigation structure
header_pages:
  - index.md
  - configuration.md
  - api.md
  - hardware.md
  - development.md
  - releases.md

# Logo settings
logo: pawvision.png
logo_width: 120

# Social links
social-network-links:
  github: mkroemer/PawVision

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
safe: true
incremental: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
