---
title: PawVision Documentation
description: A Raspberry Pi-based Pet TV system with web interface
# Use custom theme in pawvision-theme directory
layouts_dir: pawvision-theme
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: pawvision-theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

# Build settings
safe: false
incremental: false
